# Game Configurations 
GAME_CAPTION = "Aircraft Warfare"
GAME_BG_SRC = "images/background.png"
GAME_BG_SIZE = (480, 700)
GAME_FONT_SRC = "font/font.ttf"
LIFE_IMAGE_SRC = "images/life.png"
BOMB_IMAGE_SRC = "images/bomb.png"

PAUSE_NOR_IMAGE_SRC = "images/pause_nor.png"
PAUSE_PRESSED_IMAGE_SRC = "images/pause_pressed.png"
RESUME_NOR_IMAGE_SRC = "images/resume_nor.png"
RESUME_PRESSED_IMAGE_SRC = "images/resume_pressed.png"

GAMEOVER_IMAGE_SRC = "images/gameover.png"
RESTART_IMAGE_SRC = "images/again.png"

GAME_MUSIC_SRC = "sound/game_music.ogg"
BULLET_SOUND_SRC = "sound/bullet.wav"
BOMB_SOUND_SRC = "sound/use_bomb.wav"
SUPPLY_SOUND_SRC = "sound/supply.wav"
GET_BOMB_SOUND_SRC = "sound/get_bomb.wav"
GET_BULLET_SOUND_SRC = "sound/get_bullet.wav"
UPGRADE_SOUND_SRC = "sound/upgrade.wav"
E3_FLY_SOUND_SRC = "sound/enemy3_flying.wav"
E1_DOWN_SOUND_SRC = "sound/enemy1_down.wav"
E2_DOWN_SOUND_SRC = "sound/enemy2_down.wav"
E3_DOWN_SOUND_SRC = "sound/enemy3_down.wav"
PLAYER_DOWN_SOUND_SRC = "sound/me_down.wav"
VOLUME_SMALL = 0.2
VOLUME_MEDIUM = 0.5
VOLUME_FULL = 1.0

INITIAL_SMALL_ENEMIES_NUM = 4
INITIAL_MEDIUM_ENEMIES_NUM = 2
INITIAL_LARGE_ENEMIES_NUM = 1

L2_SMALL_ENEMIES_INCRE = 1
L3_SMALL_ENEMIES_INCRE = 2
L4_SMALL_ENEMIES_INCRE = 3
L5_SMALL_ENEMIES_INCRE = 4

L2_MEDIUM_ENEMIES_INCRE = 1
L3_MEDIUM_ENEMIES_INCRE = 2
L4_MEDIUM_ENEMIES_INCRE = 2
L5_MEDIUM_ENEMIES_INCRE = 3

L2_LARGE_ENEMIES_INCRE = 1
L3_LARGE_ENEMIES_INCRE = 1
L4_LARGE_ENEMIES_INCRE = 2
L5_LARGE_ENEMIES_INCRE = 2

L2_SMALL_SPEED_INCRE = 0
L3_SMALL_SPEED_INCRE = 1
L4_SMALL_SPEED_INCRE = 1
L5_SMALL_SPEED_INCRE = 1

L2_MEDIUM_SPEED_INCRE = 0
L3_MEDIUM_SPEED_INCRE = 0
L4_MEDIUM_SPEED_INCRE = 1
L5_MEDIUM_SPEED_INCRE = 1

L2_LARGE_SPEED_INCRE = 0
L3_LARGE_SPEED_INCRE = 0
L4_LARGE_SPEED_INCRE = 0
L5_LARGE_SPEED_INCRE = 1

SMALL_ENEMY_SCORE = 500
MEDIUM_ENEMY_SCORE = 2000
LARGE_ENEMY_SCORE = 5000

L2_SCORE_THRESHOLD = 50000
L3_SCORE_THRESHOLD = 300000
L4_SCORE_THRESHOLD = 600000
L5_SCORE_THRESHOLD = 1000000

MEDIUM_FONT_SIZE = 36
LARGE_FONT_SIZE = 48

INITIAL_LIFE_NUM = 3
INITIAL_BOMB_NUM = 3

SUPPLY_TIME_DURATION = 30 * 1000
INVINCIBLE_TIME_DURATION = 5 * 1000
DOUBLE_BULLET_TIME_DURATION = 18 * 1000

SCORE_TEXT_POSITION = (10, 5)
RECORD_SCORE_TEXT_POSITION = (50, 50)
RECORD_SCORE_FILE_NAME = "record.txt"

BLACK = (0, 0, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
WHITE = (255, 255, 255)
